version: '3' # composeファイルのバーション指定
services:
  app: # service名
    container_name: go_atcoder
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
